framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
          - doctrine_transaction
      query.bus:
        middleware:
          - validation
      event.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
        middleware:
          - validation
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          delay: 30_000
          multiplier: 10
          max_delay: 300_000
      sync: 'sync://'
      email:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          delay: 30_000
          multiplier: 10
          max_delay: 300_000

    routing:
      App\Core\Domain\Application\CQRS\Message\Event: async
      App\Security\Domain\UseCase\RequestForgottenPassword\Input: async

when@dev:
  framework:
    messenger:
      transports:
        sync: 'sync://'
        async: 'sync://'
        email: 'sync://'

when@test:
  framework:
    messenger:
      transports:
        sync: 'sync://'
        async: 'sync://'
        email: 'sync://'

