security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        security_user_provider:
            id: App\Security\Infrastructure\Symfony\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: security_user_provider
            login_link:
                check_route: login_check
                signature_properties: ['userIdentifier']
                max_uses: 1
                success_handler: App\Security\Infrastructure\Symfony\Security\Authentication\AuthenticationSuccessHandler
    access_control:
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
