security_controllers:
    resource:
        path: ../src/Security/UserInterface/Controller/
        namespace: App\Security\UserInterface\Controller
    type: attribute
    prefix: /api/security/
    name_prefix: security_
login_check:
    path: /login_check
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: 'https://legacy.example.com/doc'
        permanent: true