services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Core\Domain\CQRS\Handler:
            tags: ['messenger.message_handler']

    Tests\Fixtures\:
        resource: '../tests/Fixtures/'

    App\Core\Domain\CQRS\EventBus: '@Tests\Fixtures\Core\Infrastructure\Symfony\CQRS\FakeEventBus'
