parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Core\Domain\UseCase\Handler:
      tags: ['messenger.message_handler']

  App\:
    resource: '../src/'
    exclude:
      - '../src/*/Domain/Model/'
      - '../src/*/Domain/UseCase/**/Input.php'
      - '../src/*/Domain/UseCase/**/Output.php'
      - '../src/Core/Infrastructure/Symfony/Kernel.php'
      - '../src/*/Infrastructure/Doctrine/Entity/'

  app.security.user_provider:
    class: App\Security\Infrastructure\Symfony\Security\UserProvider

  App\Core\Infrastructure\Alice\Locator\OrderedFixturesLocator:
    arguments:
      - '@hautelook_alice.locator.environmentless'

  hautelook_alice.locator: '@App\Core\Infrastructure\Alice\Locator\OrderedFixturesLocator'

  core.alice.factories.pending_one_time_password:
    class: App\Core\Infrastructure\Alice\Factory\PendingOneTimePasswordFactory
    public: true

  security.alice.factories.user:
    class: App\Security\Infrastructure\Alice\Factory\UserFactory
    public: true
