parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    App\Core\Domain\Application\CQRS\Handler\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Core\Domain\Application\CQRS\Handler\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
    App\Core\Domain\Application\CQRS\Handler\EventHandler:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

  App\:
    resource: '../src/'
    exclude:
      - '../src/*/Domain/Model/'
      - '../src/*/Domain/UseCase/**/Input.php'
      - '../src/*/Domain/UseCase/**/Output.php'
      - '../src/Core/Infrastructure/Symfony/Kernel.php'
      - '../src/*/Infrastructure/Doctrine/Entity/'

  app.security.user_provider:
    class: App\Security\Infrastructure\Symfony\Security\UserProvider

  App\Core\Infrastructure\Alice\Locator\OrderedFixturesLocator:
    arguments:
      - '@hautelook_alice.locator.environmentless'

  hautelook_alice.locator: '@App\Core\Infrastructure\Alice\Locator\OrderedFixturesLocator'

  core.alice.factories.pending_one_time_password:
    class: App\Core\Infrastructure\Alice\Factory\PendingOneTimePasswordFactory
    public: true

  security.alice.factories.user:
    class: App\Security\Infrastructure\Alice\Factory\UserFactory
    public: true

  Tests\Fixtures\:
    resource: '../tests/Fixtures/'
    exclude:
      - '../tests/Fixtures/*/Domain/Model/'
      - '../tests/Fixtures/*/Domain/UseCase/**/Input.php'
      - '../tests/Fixtures/*/Domain/UseCase/**/Output.php'
      - '../tests/Fixtures/*/Infrastructure/Doctrine/Entity/'
      - '../tests/Fixtures/Core/Infrastructure/Symfony/FakeEventBus.php'
