parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $signingKey: '%env(APP_SECRET)%'

  _instanceof:
    App\Core\Domain\Application\CQRS\Handler\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Core\Domain\Application\CQRS\Handler\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
    App\Core\Domain\Application\CQRS\Handler\EventHandler:
      tags:
        - { name: messenger.message_handler, bus: event.bus }
    App\Core\Infrastructure\Alice\Provider\Provider:
      tags:
        - { name: nelmio_alice.faker.provider }

  App\:
    resource: '../src/'
    exclude:
      - '../src/*/Domain/Model/'
      - '../src/*/Domain/UseCase/**/Input.php'
      - '../src/*/Domain/UseCase/**/Output.php'
      - '../src/Core/Infrastructure/Symfony/Kernel.php'
      - '../src/*/Infrastructure/Doctrine/Entity/'

  App\Security\Infrastructure\Alice\Locator\OrderedFixturesLocator:
    arguments:
      - '@hautelook_alice.locator.environmentless'

  hautelook_alice.locator: '@App\Security\Infrastructure\Alice\Locator\OrderedFixturesLocator'

  Faker\Generator:
    factory: ['App\Core\Infrastructure\Faker\FakerFactory', 'create']

  app.security.user_provider:
    class: App\Security\Infrastructure\Symfony\Security\UserProvider
